### ISSUE TITLE
Tabs/spaces?

### ISSUE THREAD

**Issue by gabriel** [keybase/go#100]
I hesitate to even bring this up but just noticed it in to protocol repo:

http://glui.me/v1/?i=773nukp7fx3is2e/2015-01-22_at_1.06_PM_(1).png

**Comment by maxtaco** [comment]
Hahahaha!

**Comment by patrickxb** [comment]
hahaha...i'm used to go fmt fixing everything for me.

will fix.

**Comment by malgorithms** [comment]
An indent should be 2 spaces, with a tab sandwiched in the middle.

**Comment by gabriel** [comment]
mmm tab sandwich

**Comment by patrickxb** [comment]
I think I fixed them all...

**Comment by malgorithms** [comment]
hah, "tab sandwich".
