### ISSUE TITLE
Identify shows proofs in random order

### ISSUE THREAD

**Issue by gabriel** [keybase/go#104]
`client id max` might show hackernews, twitter, github and then `client id chris` might show https twitter github etc.

In the UI client, its also random when calling `identifyDefault`.

It should be ordered by "importance" I guess or some consistent order like the website, twitter, github...

**Comment by maxtaco** [comment]
Good call, I ignored this issue...

**Comment by maxtaco** [comment]
How about an mtime sort for now?

**Comment by maxtaco** [comment]
This would mean:
 - [ ] Put an mtime into `RemoteProof` objects
 - [ ] Sort by mtime in `ExportToUncheckedIdentity`
