### ISSUE TITLE
RPC-API: Include identifier on RemoteProof record

### ISSUE THREAD

**Issue by gabriel** [keybase/go#107]
It would be useful to have a proof id on the `RemoteProof` record, so I can mark a proof as successful that I have displayed in the UI (after `identifyUi.launchNetworkChecks`).

Currently in the UI code I'd have to lookup the displayed proofs by `proofType` and `value`.

**Comment by gabriel** [comment]
sigId is coming back null?

```json
{
  "sigId" : null,
  "value" : "chriscoyne.com",
  "key" : "https",
  "proofType" : 1000,
  "mtime" : 1408376008,
  "diplayMarkup" : "chriscoyne.com"
}
```

**Comment by maxtaco** [comment]
Hmm, how are you generating those JSON blobs out of msgpack blobs?  It could be an error there.  Patrick's code looks right to me.  The sketchy this is that a sigid can never be null. It's a fixed-size byte array.  At worst, it can be 32 0's.

**Comment by gabriel** [comment]
oh yeah totally could be my fault... i'll double check

**Comment by gabriel** [comment]
yeah this is totally my fault.. a bug in msgpack objc lib
