### ISSUE TITLE
RPC-API: Track remote

### ISSUE THREAD

**Issue by gabriel** [keybase/go#113]
I need to specify whether the track is remote or not, right?

`void track(string username, boolean isRemote);`

It looks like `trackUsed` in `IdentifyOutcome` is alway null even if I am tracking?

Should I be using `LinkCheckResult` `diff` for added/updated items and then `IdentifyOutcome` `deleted` for removed items?

Also am curious about what is `diff` vs `remoteDiff` on `LinkCheckResult`?

**Comment by maxtaco** [comment]
I'm not sure of when you want to track someone "remotely" or not.  It could be based on the result, you can decide.  The goal was for FinishAndPrompt to prompt you for that decision (we can of course change that around).

trackUsed thing sounds like a bug, I'll look into it tomorrow

yes on LinkCheckResult v deleted

remoteDiff is the status of the remoteProof, if it's changed since the track happened.  It could have been an HTTP error 500 when you tracked, but it's OK now.  Or vice-versa.  diff is a diff of the form "you used to be foo@twitter and now you're bar@twitter"...

**Comment by gabriel** [comment]
I use the identify return value which (for me) is easier to deal with than the finishAndPrompt callback. So a track method with remote param would be useful. In the tracker-popup (admin) doc, the first example it shows the default is to track remotely, though you can change the dropdown to track privately.

Also, I noticed that the track call is crashing for me, `gabrielh` calling `client track max` fails unlocking a secret key and my test account `gbrl24` tracking `max` fails with a `ERRO No sync'ed keys match our ComputedKeyFamily` error. I can get you a more detailed log tomorrow... this isn't a very useful bug report, I know :)

**Comment by maxtaco** [comment]
That bug report was perfectly adequate.  The `No sync'ed keys match...` error is now fixed. BTW, in fixing it, other downstream errors showed up.  You need to repull the local version of the site if you're testing locally.

**Comment by maxtaco** [comment]
As for the change to the API, maybe we should keep track of a track "session."  The keybase daemon already did a fair amount of work that's going to be rolled into the tracking statement.  It probably seems the right idea to hold onto that state, and await for approval from the UI. 

So just to summarize, the proposal is:
  1. Run identify() and display the results as we do now.  Identify() also yields some sort of "session" ID, maybe the session we already have.
  2. Then you call track(session, localOrRemote) to finish the protocol

This seems reasonable and is only a small refactor on the server side.

**Comment by maxtaco** [comment]
Finally, as for the TrackUsed being `null`, as it stands now, Identify works without any attention paid to your previous track of the user.  We can of course change that.  `track()` on the other hand, does load the previous tracking statement.  But I assume you're calling `identify` and then `track`?  Maybe we should slice up these calls in a different way.

**Comment by maxtaco** [comment]
Hmm, @gabriel, the more I look at the code, the more challenging it might be to split it up the way you want.  Can it work to just sit on the callback until the user decides?
