### ISSUE TITLE
DeviceEngine should write deviceId to config.json

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#135]
DeviceEngine should:
  * Check and see if there's already a registered deviceID for this device, and bail if so.
  * Write deviceId to config.json after running

Implications:
  * A device without a deviceId in config.json should be counted as an unprovisioned device.
  * We should maybe have a ReprovisionEngine that tries to guess what your current device is as a result of which secret keys are available in your local keychain, cross-reference that list with the ComputedKeyFamily, and write that deviceID out to `config.json`.

**Comment by maxtaco** [comment]
I did the first little bit of this in 420c5ca8d2b1073c05d9ebd473ba45243d981ad8, just writing `device.id` to `config.json`.

**Comment by patrickxb** [comment]
I did some more in 09fee2558e4e2084ad5ebde51e323bba652a369c
Device engine will bail if there's a deviceID in config.

The ReprovisionEngine is a bigger project, related to #124 and doctor command idea.  Perhaps we should split that into a different issue.
