### ISSUE TITLE
Support Multiple Users

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#153]
We keep coming back to this, and we're not too far from getting it done, so I propose the following:

## Config.json
 - [x] Move the device stanza into the user staza
 - [x] Have an `all_users : { max : {}, max_sock_puppet : {} }` dictionary that lists all users who have ever logged in or signed up on this device. The logged-in user's stanza will appear twice, once in this list, and once in the `all_users` dictionary.
 - [x] Maintain `config.json` on login and logout as described above.

## secrets.mpack should be per-user
  - [x] Add the user's login name into his `secret.mpack` file so that `max` and `max2` have different keyrings. 

## leveldb changes
  - [x] Change local track row keys to be `u1.u2`, if u1 is tracking u2

## cmd_login
  - [ ] Change `cmd_login` to accept a username argument.  If no username given, then try to log in as `current_user`; if one is given, switch username to new `current_user`.

**Comment by maxtaco** [comment]
cc @gabriel, I think this would greatly simplify his testing.

**Comment by patrickxb** [comment]
looks good to me.

**Comment by maxtaco** [comment]
Closed in 5e6b4b857c1fdb4de0eaf9a1e84036c11e07821b
