### ISSUE TITLE
FindActiveSibkey and IsKidActive should share code...

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#158]
Right now they reimplement the same checks.

**Comment by oconnor663** [comment]
"Find" might be a bad word to begin with. It's taking a FOKID, so it's not exactly searching, just looking up.

Also "Active" is tricky. Sometimes we meed "active now" and sometimes we mean "active when X signature was made."

**Comment by oconnor663** [comment]
Just pushed https://github.com/keybase/go/tree/jack_issue158 with some simple name changes, and one question in a TODO. Let me know if those make sense to you, @maxtaco.

**Comment by oconnor663** [comment]
We seem to go back and forth between "live" and "active". Which one do you prefer?

**Comment by oconnor663** [comment]
Pushed a couple more, last one deletes `findLiveComputedKeyInfo` entirely and has its former callers use `IsFOKIDActive` and `IsKidActive`.

**Comment by oconnor663** [comment]
Here's the compare view that lets you see everything at once: https://github.com/keybase/go/compare/jack_issue158

**Comment by maxtaco** [comment]
Live is fine, but be sure to s/Active/Live/g everywhere.

As for the Now vs. Then issue, can we change the signatures so that they either (1) take a timestamp or (2) explicit refer to Now()?

**Comment by oconnor663** [comment]
Note to self: Rename `KEY_LIVE` to something more explicitly not about etime.

**Comment by oconnor663** [comment]
Note to self: after #88 is in, move the timestampchecking logic that's in `VerifySigWithKeyFamily` so that it's no longer duplicated. `FindActiveSibkey` (or whatever we call it) should take care of that for us, when we give it the link's ctime.

**Comment by oconnor663** [comment]
Paved that branch (https://github.com/keybase/go/tree/jack_issue158) with a bunch of new commits, and tests are passing. Ready for review, @maxtaco.

**Comment by maxtaco** [comment]
Ready when you are!
