### ISSUE TITLE
RPC-API: Return unique error code for "You are already logged in as a different user; try logout first"

### ISSUE THREAD

**Issue by gabriel** [keybase/go#173]
```
Sent request: keybase.1.config.getCurrentStatus({})
Result: {
    configured = 1;
    loggedIn = 1;
    registered = 0;
}

Sent request: keybase.1.login.passphraseLogin({
    identify = 0;
    passphrase = "[FILTERED]";
    username = gbrl;
})

Error: Error Domain=MPMessagePack Code=218 "You are already logged in as a different user; try logout first" UserInfo=0x608000269a40 {NSLocalizedDescription=You are already logged in as a different user; try logout first}
```

Can you make this a unique error code (instead of generic/218)? Because I don't get a user from status (even though it says logged in?), I don't know if I need to give the user an option to logout.

If it returns a specific error code for "logged in as different user", I can prompt the user to see if they really wanted to switch users.

**Comment by maxtaco** [comment]
Sorry, on it...

**Comment by maxtaco** [comment]
Ok, should be done:

`"ALREADY_LOGGED_IN"` or code `235`

Let me know if you see any other weird issues with Login.  I made a bunch of changes to it yesterday to use pubkey-style logins by default.
