### ISSUE TITLE
web user w/ pub pgp key has nil ComputedKeyFamily, empty active pgp keys

### ISSUE THREAD

**Issue by patrickxb** [keybase/go#174]
Steps to reproduce:

1. create a user via web
2. use web to generate pgp key
3. don't store private key on web
4. during go client login checks, user.GetComputedKeyFamily() is nil.

Also, expecting user.GetActivePgpKeys(false) to return one key, but it is empty.

**Comment by patrickxb** [comment]
more info:

u.sigChain.GetComputedKeyInfos() returns nil

**Comment by oconnor663** [comment]
`verifySubchain` needs to return valid data in the case where links is `nil`. Then I'll talk to @maxtaco or @patrickxb about how to write a test for this.

**Comment by oconnor663** [comment]
In this case we'll pull your PgpKeyBundle straight from the KeyFamily (Sibkeys[eldest]), and we need to refactor some of the inner logic out of InsertEldestLink so that we can get the ctime/etime and confirm that the Keybase username is signed into the key properly.
