### ISSUE TITLE
modernize libkb/keygen

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#193]
It probably should become an engine.  And possibly it shouldn't be calling login, its caller should have..

See #192 for related bug.

**Comment by patrickxb** [comment]
I agree.

**Comment by maxtaco** [comment]
KeygenUI/Protocol should be combined with GPGUI/Protocol.  They have common code (do you want to push?)

**Comment by maxtaco** [comment]
Strip out all NaclGen stuff too...

**Comment by maxtaco** [comment]
Also, there's a lot of dup'ed copy/paste code with sibkeyPost and primaryPost.  Fold into one function

**Comment by maxtaco** [comment]
More code dedupe:  naclgen and gpgkeygen have very similar push functions.

**Comment by maxtaco** [comment]
More progress in ac55e9b.

**Comment by maxtaco** [comment]
Also, both PgpKeyGen and NaclKeyGen run the same generate/post/save loop.  Should be maybe merged into one template.
