### ISSUE TITLE
RPC-API: No field info on missing or invalid input error

### ISSUE THREAD

**Issue by gabriel** [keybase/go#194]
Low priority...

If I give a weird input for email (that the client itself doesn't catch I get an error: `100 missing or invalid input`), but it doesn't set the field:

For example, 

```
keybase.1.signup.signup({
  email = "invalidemailaddress"
  ...
});
```

Returns error:

```
{
    code = 100;
    desc = "missing or invalid input";
    fields = "<null>";
    name = "INPUT_ERROR";
}
```

**Comment by maxtaco** [comment]
ah i think i know why.  i don't think it's being exported properly from the daemon
