### ISSUE TITLE
Signup calling keybase.1.mykeyUi.getPushPreferences even though I'm using selectKeyAndPushOption

### ISSUE THREAD

**Issue by gabriel** [keybase/go#211]
When I call signup, its asking me for push preferences (`keybase.1.mykeyUi.getPushPreferences`) after I import my PGP key even though I'm using `gpgUi.selectKeyAndPushOption`?

**Comment by maxtaco** [comment]
This might a regression with our most recent refactor. Is it blocking you?

**Comment by maxtaco** [comment]
I think we can fix this along with #193

**Comment by maxtaco** [comment]
This should be closed along with #193.  Please let me know if you hit any bugs.
