### ISSUE TITLE
RPC-API: Calling logout and login with same user a lot causes an expired error on login

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#56]
<a href="https://github.com/gabriel"><img src="https://avatars.githubusercontent.com/u/2669?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gabriel](https://github.com/gabriel)**
_Wednesday Jan 07, 2015 at 02:04 GMT_
_Originally opened as https://github.com/keybase/go-libkb/issues/74_

----

I've been logging in and out a lot while testing, and now when I try to login with my test user (username=gbrl24) I get the error: 

```for uid b7c2eaddcced7727bcb229751d91e800: Expired 3347s ago```

go-keybased log:
```
18:00:36.908870 ▶ DEBU 115 {unix} serve(2): method=keybase.1.login.passphraseLoginNoIdentify; err=null; arg={"Username":"gbrl24","Passphrase":"XXXXX"};
18:00:36.908910 ▶ DEBU 116 + Login called
18:00:36.908927 ▶ DEBU 117 + LoginState.login (username=gbrl24)
18:00:36.908940 ▶ DEBU 118 + Loading session
18:00:36.908953 ▶ DEBU 119 - Skipped; already loaded
18:00:36.908965 ▶ DEBU 11a | got username: gbrl24
18:00:37.037698 ▶ DEBU 11b + API Post request to https://api.keybase.io:443/_/api/1.0/login.json
18:00:37.520935 ▶ DEBU 11c | Result is: 200 OK
18:00:37.521107 ▶ DEBU 11d - LoginState.login -> ERROR
18:00:37.521148 ▶ DEBU 11e {unix} reply(2): method=keybase.1.login.passphraseLoginNoIdentify; err=Failure from server: for uid b7c2eaddcced7727bcb229751d91e800: Expired 3347s ago (error 202); res=null;
```

This is not blocking, as I can nuke my local state to fix.

Btw, a command to nuke local caches would be cool... removing stuff from .config, .cache, etc all in one swoop. Could be dangerous though I guess.

**Comment by maxtaco** [comment]
<a href="https://github.com/maxtaco"><img src="https://avatars.githubusercontent.com/u/866815?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxtaco](https://github.com/maxtaco)**
_Wednesday Jan 07, 2015 at 02:09 GMT_

----

Hmm, interesting.  I'll put in the queue.

**Comment by gabriel** [comment]
I still get this pretty often...

http://glui.me/?i=jpofpc9su1vwa1e/2015-01-20_at_3.59_PM_2x.png/

Should be able to replicate it by logging in on the UI, choosing logout from status menu and then log back in.

**Comment by maxtaco** [comment]
@gabriel  is this issue fixed?

**Comment by gabriel** [comment]
yeah probably.. if I ever see it again re-open

**Comment by maxtaco** [comment]
Cool, a lot has changed there, so hopefully it's gone. thanks!
