### ISSUE TITLE
keygen: Allow inclusion of other email in generated key...

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#60]
<a href="https://github.com/maxtaco"><img src="https://avatars.githubusercontent.com/u/866815?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maxtaco](https://github.com/maxtaco)**
_Friday Jan 09, 2015 at 03:02 GMT_
_Originally opened as https://github.com/keybase/go-libkb/issues/80_

----

..in addition to the foo@keybase.io email

**Comment by maxtaco** [comment]
More information:
* See [keygen.go](https://github.com/keybase/go/blob/master/libkb/keygen.go#L52) for our convenient shortcut
* Probably an upgrade to KeyGenArg to toggle default KB userId.

**Comment by patrickxb** [comment]
My commit allows you to specify a -e, --email option to the mykey gen subcommand.  This email address will replace the foo@keybase.io email address.

Let me know if multiple identities are preferred:  adding an identity with the email address and keeping the foo@keybase.io identity alongside it.

**Comment by maxtaco** [comment]
Thanks @patrickxb.  We definitely want to add foo@keybase.io in addition by default, but maybe have a switch to turn that off.  Also, some people legitimately want to put multiple emails in their key.  So can `-e` or `--email` take multiple addresses?  I think we want that...

**Comment by patrickxb** [comment]
Ok, will make that work.  What should the username be in the identity for the custom emails?  Empty?

**Comment by maxtaco** [comment]
Yes, but maybe you should also accept `--uid "Maxwell Krohn (born 1977) <themax@gmail.com>`-style UIDs?  We have a parser for those I think.

**Comment by maxtaco** [comment]
Look at `ParseIdentity` for how to parse that stuff.  Just uses a regex.

**Comment by NiklasBr** [comment]
@patrickxb sorry I resurrect an old issue. What happened to multiple email addresses?

I have encountered a scenario which I think would benefit from multiple email addresses, consider a person who is self-employed or working as a consultant, this person's company is myfoo.com, and has already registered and verified bar@myfoo.com with Keybase.

Now this person gets hired as a contractor for a year or so at bazco.com, gets a temporary bar@bazco.com address and is invited to the Keybase team at bazco.com with this address. Now it would be useful for this consultant to be able to verify that the same person who controls bar@myfoo.com also controls bar@bazfo.com and is therefore the same person.

As I understand it, there are no ways of doing this at the moment. Is it planned? Can I request the feature?

**Comment by patrickxb** [comment]
@NiklasBr When an admin of the bazco Keybase team invites bar@bazco.com to the team, the invite token that bar@bazco receives via email can be used by a keybase user who has registered and verified bar@myfoo.com to join the bazco Keybase team.

The bar@bazco.com email address will not be associated with their account, it's just a way to deliver the invite token for the bazco team to this person.

**Comment by NiklasBr** [comment]
Thanks @patrickxb, I never considered the fact that tokens were not tied to the email of the invited user. This answers and solves about 90% of my question. :) The only thing I am missing is the ability to add secondary email addresses. Are there any plans?
