### ISSUE TITLE
cmd: mykey select

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#61]
<a href="https://github.com/maxtaco"><img src="https://avatars.githubusercontent.com/u/866815?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maxtaco](https://github.com/maxtaco)**
_Wednesday Jan 07, 2015 at 02:11 GMT_
_Originally opened as https://github.com/keybase/go-keybased/issues/5_

----

Port over to client/server

**Comment by maxtaco** [comment]
<a href="https://github.com/maxtaco"><img src="https://avatars.githubusercontent.com/u/866815?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxtaco](https://github.com/maxtaco)**
_Wednesday Jan 07, 2015 at 02:13 GMT_

----

cc: @gabriel

**Comment by maxtaco** [comment]
(Patrick, this is one of the more complicated issues.  The background is that `client mykey select` used to work as a standalone client, but doesn't work now in Client-Server mode.  I've been slowly porting subcommands over to this system.  Probably do this one in a branch so I can code review it with you).

**Comment by maxtaco** [comment]
This is related to #126

**Comment by patrickxb** [comment]
yes, I should be able to reuse all the code for this...
