### ISSUE TITLE
keybase config <setter> crashes if no config file

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#63]
<a href="https://github.com/maxtaco"><img src="https://avatars.githubusercontent.com/u/866815?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maxtaco](https://github.com/maxtaco)**
_Thursday Nov 13, 2014 at 19:28 GMT_
_Originally opened as https://github.com/keybase/go-client/issues/8_

----

**Comment by patrickxb** [comment]
Is this still an issue?  I couldn't reproduce it.

**Comment by maxtaco** [comment]
I did do a refactor here a few weeks ago.  So maybe not...

**Comment by patrickxb** [comment]
I'll close it then.  Seems fine to me.
