### ISSUE TITLE
RPC-API: load users for display (without identification)

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#68]
A method to load a user (not really identifying tho, more just like for display:

```go
array<User> users(array<string> usernames)
```

**Comment by gabriel** [comment]
Now that we have a User object started would be good to have some extra stuff for the UI client:

```
record User {
  UID uid;
  string username;
  // To add
  array<Image> images;
  string fullname;
  string bio;
  string location;
}

record Image {
  string url;
  int width;
  int height;
}
```

**Comment by gabriel** [comment]
Identify will give me key, proof and cryptocurrency info but would be good to have it initially so I can display in the UI while its identifying.

record User {
  ...
  array<Proof> proofs;
  array<Cryptocurrency> cryptocurrency;
  array<PublicKey> publicKeys;
}

Basically in some of the same stuff the API does: https://keybase.io/docs/api/1.0/user_objects

Currently, just so I'm not blocked, I'm using the web API to load user objects.

**Comment by maxtaco** [comment]
This should already be implemented. Before the network checks are launched, there's this call:

```c
void launchNetworkChecks(int sessionId, Identity id);
```

**Comment by gabriel** [comment]
ok cool... I guess still need the user image?

```
record User {
  ...
  array<Image> images;
}

record Image {
  string url;
  int width;
  int height;
}
```

Yeah this is better since it's good not to show anything that hasn't been verified.

I'll create a separate ticket for getting the image.

**Comment by maxtaco** [comment]
@gabriel, ok to close this issue?
