### ISSUE TITLE
RPC-API: identify

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#69]
Not just for login, for ongoing use:

```go
void verify(username string); // --- OR ---
void verify(uid UID);  
```

**Comment by maxtaco** [comment]
@gabriel do you mean track() or identify()?  I'm not totally sure what verify() is. Typically it refers to verifying sigs.

**Comment by gabriel** [comment]
I think identify. When I display a user profile view, it would be good to show if/when/what proofs have been verified (or update, trigger checks if its old).
Like when you do `client id max`.

**Comment by maxtaco** [comment]
Ok, @patrickxb  is on it.

**Comment by patrickxb** [comment]
Closed with merge of branch issue_69.

**Comment by gabriel** [comment]
Probably want to rename `user` arg to `username`?

So for most calls, I'll want to use the right defaults and don't want to encode it in the client in case the default changes? (Basically we want to push as much logic as possible into the daemon.)

So we could change the identify call to: `void identify(string username);`, if uid required?

**Comment by gabriel** [comment]
It would also be cool if it returned the outcome instead of using  `keybase.1.identifyUi.finishAndPrompt`.
e.g. `IdentifyOutcome identify(string username);`

**Comment by patrickxb** [comment]
I'm fine renaming `user` to `username`.  

Either `uid` or `username` is required.  The daemon will use `uid` first and `username` if `uid` doesn't exist.  This was a translation of how the standalone command line client worked.

What about adding another function like `identifySimple(string username)`?  That way this one with all the options can stay, but you can use the easier one.

**Comment by gabriel** [comment]
sounds good... maybe use `identifyDefault` which is the convention we use for keyGen.

**Comment by patrickxb** [comment]
Ok, `identify` and `identifyDefault` are in place.

Both return `IdentifyRes` which includes `IdentifyOutcome` and `User`. (`User` was needed elsewhere...)
