### ISSUE TITLE
Daemon: Cleanup socket file after crash?

### ISSUE THREAD

**Issue by gabriel** [keybase/go#76]
My computer crashed and when I came back and tried to start daemon.

```
➜ ~/Projects/go/src/github.com/keybase/go/daemon (master) ./daemon 
▶ INFO Binding to unix:/tmp/keybase-gabe/keybased.sock 
▶ ERRO listen unix /tmp/keybase-gabe/keybased.sock: bind: address already in use 
```

After checking to make sure daemon wasn't running. I removed the file and started it up.

I'm picturing this happening and OS X not (re-)starting the daemon because of this error and us getting support tickets.

**Comment by maxtaco** [comment]
Good point.

The one issue will be mistakenly restarting a second keybased, when the first one was running all along.  

We should probably use some sort of `fcntl` or `flock` file locking to have a lock that will be dropped when the process exits to ensure that there's only one keybased running at a time.  This is a fairly routine unix problem that hopefully has a good answer, but you never know, file locking is notoriously frustrating.

**Comment by gabriel** [comment]
BTW, this is reproducable if:

- Start daemon
- Run kill on the pid
- Daemon stops
- Try to restart daemon, gets bind error

I know that /var/run doesn't persist on restart. Maybe we should be using a pid file for running (and socket file is always removed on start if present).

This stackoverflow has some good links it seems:
http://stackoverflow.com/questions/688343/reference-for-proper-handling-of-pid-file-on-unix

There is always, check for process, if doesn't exist and pid file does, remove the pid.

**Comment by maxtaco** [comment]
That's what I had in mind --- a pidfile in run and a socket somewhere else. 

An issue is that /var/run isn't writable by regular users.  So we might need to stick with /tmp

That's a great pointer from the SE thread, let's go with something like that.

**Comment by maxtaco** [comment]
Slight worry....what if the PID counter wraps?

**Comment by patrickxb** [comment]
All the way around to the exact pid of its predecessor?  It could happen.

I can Flock() the file descriptor.  Are os x and linux the only platforms we're concerned about?

**Comment by maxtaco** [comment]
It's not likely to happen to one user, but across all users, it's guaranteed to happen, and we'll get a support ticket that their thing won't restart.  The pid space is pretty small (2^16).  

I started down the path of windows support.  Maybe we can go with the pid strategy for windows and the flock strategy for OSX and Linux.

**Comment by patrickxb** [comment]
The pid file is stored in the RuntimeDir, which is user-specific...

On a device, there's one instance of keybased running for each concurrent user, correct?

**Comment by maxtaco** [comment]
Right, for each OS-level user, one keybased. I was thinking most desktop/client machines these days only run with one user anyway.  I don't think the per-user-ness of the pidfile buys you much in terms of wraps not happening.

**Comment by patrickxb** [comment]
Ok, well I can check if the pid in the file matches the current pid.  That should handle the wrap.
