### ISSUE TITLE
"Please login again to verify your public key"

### ISSUE THREAD

**Issue by gabriel** [keybase/go#77]
On keybase.1.login.passphraseLogin when I have a public key set but no hosted proofs. 

This is what the client does:

```
./client login
Your keybase username or email: gbrl24
▶ WARN Verifying your fingerprint... 
✔ public key fingerprint: 1F13 DD87 B56D 20DF CE92 118A BA34 2036 07EA BE24
We found your account, but you have no hosted proofs. Check your fingerprint carefully. Is this you? (type 'YES' to confirm):
```

Wondering what I should do in the UI...

**Comment by gabriel** [comment]
There is no way to clear a selected key... maybe `client mykey clear`?

**Comment by maxtaco** [comment]
Indeed.  For now you can use the local website to click "revoke or replace my public key" (it's hidden in the gear).

Shouldn't be too bad, just need to find time.

**Comment by maxtaco** [comment]
(see #79)

**Comment by maxtaco** [comment]
@malgorithms  what do you think about this one?  It's U/X related...

**Comment by malgorithms** [comment]
Max and I talked about this a bunch. This system has to change as a result of how sibling keys will work.

Currently keybase is about this one PGP key. Soon:

   - every device will have its own "sibling" key (a NaCl key)
   - if you use the Keybase website, you'll get one sibkey for web usage, too, which is a function of your keybase password.
   - finally, your PGP key may exist on one or more of your devices, but that's a tangential issue.

Adding a new device involves taking a previous device and connecting them as siblings. Basically a 2-way proof. (More on this process in a second.) If, for some reason, you can't do that, say you lost all your previous devices, then you'll need to start totally fresh.

The mechanics of adding device B when you have device A:

This is done by the key pairs on A and B signing statements about each other. To do this, the simplest way is to open a secure channel between A and B, so they can generate signed statements about each other. And the easiest way for devices A and B to open a secure channel is for them to share a secret.

All of these work:

1. device A could take a screenshot of a QR code on device B, which contains a secret.
1. device B could take a screenshot of a QR code on device A, which contains a secret
1. the user could type ~10 random words into device A, which they read from device B.
1. the user could type ~10 random words into device B, which they read from device A.

Note the symmetry here: the secret can be generated on either device and verified/used on the other. 

So, for example, if someone signs up on the web, the most logical way for them to add their phone is to take a screenshot of a QR code on the website.

And if they sign up on their phone, the most logical way to add a website key is actually the same -- to take a photo of a QR code with their phone.

If someone is on a desktop and needs to add a laptop, or vice versa, and there are no cameras available, they'll need to type in some words. Fortunately with every device I can think of, where there is no camera there is always a keyboard.

Anyway, how this all comes back to Gabriel's question... when you sign in on a new device, this process of reviewing your PGP key won't be necessary. Instead you'll need to take one of the 4 steps above. If you can't, you have to reset your account and start fresh.

**Comment by gabriel** [comment]
Cool, so it sounds like when a user logs in the status object **shouldn't** send back `hasPrivateKey` or `publicKeySelected` but should send back:

- `needsPrivateKey` (If they created an account but never generated a private key)
- `needsDeviceKey` (If they are logging into a new device)

And then we'll need separate rpc for generating a private key or device key. (`keyGenPrivate...`, `keyGenDevice...`). Generating/selecting a private key is straight forward, but as you mention above creating a device key requires work (options 1-4)?

**Comment by maxtaco** [comment]
We're scrapping this feature as we merge #85.  Happening soon.

**Comment by maxtaco** [comment]
@gabriel has this issue been fixed for you?

**Comment by gabriel** [comment]
yep fixed
