### ISSUE TITLE
Daemon: Username missing

### ISSUE THREAD

**Issue by gabriel** [keybase/go#81]
This is not blocking me, just noticed it.

The daemon is sending empty string for username (on status and other things like password prompt). 
This is for my current test user `gbrl24`.

```
cat ~/.config/keybase/config.json 
{
    "user": {
        "fingerprint": "0092e388482dec1976804e2827673e2c2e11e85d",
        "id": "04c89fea249a00c1005a8b3897325100",
        "salt": "246b1ec5a3cab30eeeed05f906a03101"
    }
}
```

**Comment by gabriel** [comment]
nm, logged out and back in and fixed..

**Comment by maxtaco** [comment]
Still, I've noticed this issue too....  It might come back...
