### ISSUE TITLE
RPC-API: What does proveUi.promptOverwrite1 mean? Maybe we should have a generic UI prompt command?

### ISSUE THREAD

**Issue by gabriel** [keybase/go#83]
I assume that proveUi.promptOverwrite1 means to ask to verify that we're gonna generate a new proof sig and everything. 

So I can keep the UI stupid, maybe we should have a generic prompt method?

**Comment by maxtaco** [comment]
Yeah, let me look into refactoring it a bit.  It grew out of the various control paths of the tex-based protocol.
