### ISSUE TITLE
Need a server-side devices table

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#89]
Should have the following columns:
  - uid
  - deviceid (generated randomly)
  - ctime
  - mtime
  - description
  - type (web browser, OSX client, iOS client, etc)
  - the server half of the local encryption key

Required subtasks:
  - [x] Post on signup
  - [x] Post on login from a new device
  - [x] Publish in self object
  - [x] also matches some aspects of the user's sigchain

**Comment by malgorithms** [comment]
in our discussion earlier today, we decided deviceid's weren't important, temporarily. Then you came back and said "oh, I know why we need deviceids" (which I don't know if you ever ended up explaining). I'm bringing this up right now in case you want to record thoughts on this somewhere...and they're mentioned in this server-side table. :-)

**Comment by maxtaco** [comment]
(updated! the server half of the device-local symmetric encryption key)

**Comment by maxtaco** [comment]
Much of this work is being folded into #111.

**Comment by maxtaco** [comment]
Addressed in #135, #152, and others.
