### ISSUE TITLE
First time daemon startup should mkdir `/tmp/keybase-$USER`

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#92]
Right now it's failing to put a socket down, since that directory doesn't exist.

**Comment by maxtaco** [comment]
cc @malgorithms who hit this bug

**Comment by patrickxb** [comment]
I'll fix it.

**Comment by gabriel** [comment]
I think this is still a bug.. I've updated to the latest and

`rm -rf /tmp/keybase-gabe`

Then try to start and get an `error locking /tmp/keybase-gabe/keybased.pid`

**Comment by patrickxb** [comment]
I can't reproduce this.  Can you post the full command you are using to start the daemon?

**Comment by gabriel** [comment]
Oops nm, I need to alias `go get -u && go build -a` so I don't forget to do a clean build
