### ISSUE TITLE
Login and selected key can get out of sync

### ISSUE THREAD

**Issue by gabriel** [keybase/go#96]
If you login and then login with a different user, the selected key is still left over from the old user and it will return an error:

`Server gave wrong key; wanted 3f6e504945ae44e6a53d49845431890fe1eebcde; got f2f9cad51073c213d411541c0d71aa6e47233849`

**Comment by maxtaco** [comment]
The old node client has a `reset` object or a `switch` option for switching users.  Haven't reimplemented it yet.

**Comment by maxtaco** [comment]
This is related to #55

**Comment by maxtaco** [comment]
Should be fixed, feel free to reopen if not
